### PR TITLE
stream timeout value outsourced as config parameter & command method renamed from fire to handle (Laravel 5.5+)

### PR DESCRIPTION
**Pull request by bomas13**

### CODE REVIEW

**Review by danielbecker — APPROVED** [review]
Looks good to me and helps avoiding false errors with slower mail servers.

**Comment by skmetaly** [comment]
Looks good to me as well 👍  thank you for this!

**Comment by skmetaly** [comment]
@bomas13  Tagged 1.1.0 if you want to use it right away

**Comment by bomas13** [comment]
thanks. 👍

**Comment by bomas13** [comment]
Could it be that you have to push it to packagist as well?
Because I can't use your tagged version 1.1.0 within composer.

**Comment by skmetaly** [comment]
@bomas13 I just checked on https://packagist.org/packages/skmetaly/laravel-smtp-email-verifier and it seems that 1.1.0 is available there

I also updated packagist just to be sure. Can you recheck?

**Comment by bomas13** [comment]
@skmetaly yes, now it worked
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating skmetaly/laravel-smtp-email-verifier (1.0.0 => 1.1.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
```

thanks for all

**Pull request merged**
